version: '3.8'
services:
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace_order
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_DB: marketplace_product
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  order_backend:
    build: ./marketplace_order_backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/marketplace_order
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./marketplace_order_backend/src:/app/src
    depends_on:
      - postgres

  product_backend:
    build: ./marketplace_product_backend
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres2:5432/marketplace_product
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./marketplace_product_backend/src:/app/src  # Adjust path if necessary
    depends_on:
      - postgres2
  
volumes:
  postgres_data:
  postgres_data2:
